cd # ENGS 50 Module 6 Testing Script F20
# Author Brandon Guzman


./query ./ # number of arg test 
#!/bin/bash

# run  query engine on index created from 82 files generated by crawling to depth 3
./query ./ ../idxfiles/indexnm # not valid crawler dir test

./query ./ file   # unreadable file test 

valgrind ./query ../pages ../idxfiles/indexnm < error-queries.txt   # prof's error tests

valgrind query ../pages ../idxfiles/indexnm -q < good-queries.txt > myoutput  # run quietly test with professor's queries 



