#!/bin/bash

# run query engine on index created from 82 files generated by crawling to depth 3
./querier ./ ../idxfiles/indexnm   # number of arg test / not valid crawler dir test

./querier ./ file   # unreadable file test 

valgrind ./querier ../pages ../idxfiles/indexnm < error-queries.txt   # prof's error tests

valgrind ./querier ../pages ../idxfiles/indexnm -q < good-queries.txt > myoutput  # run quietly test with professor's queries
