#!/bin/bash

# run query engine on index created from 82 files generated by crawling to depth 3

# number of arg test / not valid crawler dir test
./querier ./ ../indexer/indexnm  

# unreadable file test
./querier ./ file  

# professor's error tests
valgrind --leak-check=full --show-leak-kinds=all ./querier ../pages ../indexer/indexnm < error-queries.txt  

# run quietly test with professor's queries
valgrind --leak-check=full --show-leak-kinds=all ./querier ../pages ../indexer/indexnm -q < good-queries.txt > myoutput
